/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FarmerRouteImport } from './routes/farmer'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FarmerIndexRouteImport } from './routes/farmer.index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as FarmerProfileRouteImport } from './routes/farmer.profile'
import { Route as FarmerOrdersRouteImport } from './routes/farmer.orders'
import { Route as FarmerListingsRouteImport } from './routes/farmer.listings'
import { Route as FarmIdRouteImport } from './routes/farm.$id'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRoute = FarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerIndexRoute = FarmerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FarmerRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerProfileRoute = FarmerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerOrdersRoute = FarmerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerListingsRoute = FarmerListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmIdRoute = FarmIdRouteImport.update({
  id: '/farm/$id',
  path: '/farm/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/farmer': typeof FarmerRouteWithChildren
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/orders': typeof OrdersRoute
  '/signup': typeof SignupRoute
  '/wishlist': typeof WishlistRoute
  '/farm/$id': typeof FarmIdRoute
  '/farmer/listings': typeof FarmerListingsRoute
  '/farmer/orders': typeof FarmerOrdersRoute
  '/farmer/profile': typeof FarmerProfileRoute
  '/product/$id': typeof ProductIdRoute
  '/farmer/': typeof FarmerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/orders': typeof OrdersRoute
  '/signup': typeof SignupRoute
  '/wishlist': typeof WishlistRoute
  '/farm/$id': typeof FarmIdRoute
  '/farmer/listings': typeof FarmerListingsRoute
  '/farmer/orders': typeof FarmerOrdersRoute
  '/farmer/profile': typeof FarmerProfileRoute
  '/product/$id': typeof ProductIdRoute
  '/farmer': typeof FarmerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/farmer': typeof FarmerRouteWithChildren
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/orders': typeof OrdersRoute
  '/signup': typeof SignupRoute
  '/wishlist': typeof WishlistRoute
  '/farm/$id': typeof FarmIdRoute
  '/farmer/listings': typeof FarmerListingsRoute
  '/farmer/orders': typeof FarmerOrdersRoute
  '/farmer/profile': typeof FarmerProfileRoute
  '/product/$id': typeof ProductIdRoute
  '/farmer/': typeof FarmerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/farmer'
    | '/login'
    | '/marketplace'
    | '/orders'
    | '/signup'
    | '/wishlist'
    | '/farm/$id'
    | '/farmer/listings'
    | '/farmer/orders'
    | '/farmer/profile'
    | '/product/$id'
    | '/farmer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/marketplace'
    | '/orders'
    | '/signup'
    | '/wishlist'
    | '/farm/$id'
    | '/farmer/listings'
    | '/farmer/orders'
    | '/farmer/profile'
    | '/product/$id'
    | '/farmer'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/farmer'
    | '/login'
    | '/marketplace'
    | '/orders'
    | '/signup'
    | '/wishlist'
    | '/farm/$id'
    | '/farmer/listings'
    | '/farmer/orders'
    | '/farmer/profile'
    | '/product/$id'
    | '/farmer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  FarmerRoute: typeof FarmerRouteWithChildren
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  OrdersRoute: typeof OrdersRoute
  SignupRoute: typeof SignupRoute
  WishlistRoute: typeof WishlistRoute
  FarmIdRoute: typeof FarmIdRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer': {
      id: '/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof FarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/': {
      id: '/farmer/'
      path: '/'
      fullPath: '/farmer/'
      preLoaderRoute: typeof FarmerIndexRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/profile': {
      id: '/farmer/profile'
      path: '/profile'
      fullPath: '/farmer/profile'
      preLoaderRoute: typeof FarmerProfileRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/orders': {
      id: '/farmer/orders'
      path: '/orders'
      fullPath: '/farmer/orders'
      preLoaderRoute: typeof FarmerOrdersRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/listings': {
      id: '/farmer/listings'
      path: '/listings'
      fullPath: '/farmer/listings'
      preLoaderRoute: typeof FarmerListingsRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farm/$id': {
      id: '/farm/$id'
      path: '/farm/$id'
      fullPath: '/farm/$id'
      preLoaderRoute: typeof FarmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FarmerRouteChildren {
  FarmerListingsRoute: typeof FarmerListingsRoute
  FarmerOrdersRoute: typeof FarmerOrdersRoute
  FarmerProfileRoute: typeof FarmerProfileRoute
  FarmerIndexRoute: typeof FarmerIndexRoute
}

const FarmerRouteChildren: FarmerRouteChildren = {
  FarmerListingsRoute: FarmerListingsRoute,
  FarmerOrdersRoute: FarmerOrdersRoute,
  FarmerProfileRoute: FarmerProfileRoute,
  FarmerIndexRoute: FarmerIndexRoute,
}

const FarmerRouteWithChildren =
  FarmerRoute._addFileChildren(FarmerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  FarmerRoute: FarmerRouteWithChildren,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  OrdersRoute: OrdersRoute,
  SignupRoute: SignupRoute,
  WishlistRoute: WishlistRoute,
  FarmIdRoute: FarmIdRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
